# Generated by Django 4.0.6 on 2022-07-08 08:18

import api.models.manga
import api.models.manga_pages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('media_id', models.CharField(max_length=255, unique=True)),
                ('title', models.JSONField(default=api.models.manga.Manga.title_default, validators=[api.models.manga.Manga.validate_title])),
                ('upload_date', models.DateField()),
                ('num_favorites', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': 'upload_date',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['tag_id', 'type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField()),
                ('descriptor', models.JSONField(default=api.models.manga_pages.Page.descriptor_default, validators=[api.models.manga_pages.Page.validate_descriptor])),
                ('computed', models.DateField(auto_now=True)),
                ('manga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='api.manga')),
            ],
            options={
                'ordering': ['manga_id', 'page'],
                'get_latest_by': 'computed',
            },
        ),
        migrations.AddField(
            model_name='manga',
            name='tag',
            field=models.ManyToManyField(related_name='manga', to='api.tag'),
        ),
    ]
